---
- name: download oneill
  get_url: url=http://storage.googleapis.com/rehab-labs-oneill-releases/stable/oneill dest=/usr/local/bin/oneill mode=0755 force=yes

- name: Creates directory
  file: path=/etc/oneill state=directory

- name: Upload oneill config file
  copy: src=config.yaml dest=/etc/oneill/config.yaml mode=0644

- name: Upload deploy key for definitions repo
  copy: src=definitions_repo.pem dest=/root/.ssh/id_rsa mode=0600

- git:
    accept_hostkey: true
    repo: "{{ definitions_repo }}"
    dest: "/etc/oneill/definitions"

# Update site definitions every few minutes
- cron: name="get definitions" minute="*/3" job="cd /etc/oneill/definitions; git pull"
# Run oneill container manager every 5 minutes
- cron: name="oneill" minute="*/5" job="run-one /usr/local/bin/oneill >> /var/log/oneill.log 2>&1"
