---
- name: download oneill
  get_url: url=http://storage.googleapis.com/rehab-labs-oneill-releases/stable/oneill dest=/usr/local/bin/oneill mode=0755 force=yes

- name: Creates directory
  file: path=/etc/oneill state=directory

- name: Upload oneill config file
  copy: src=config.yaml dest=/etc/oneill/config.yaml mode=0644

- name: Upload oneill container definitions
  copy: src=definitions.yaml dest=/etc/oneill/definitions.yaml mode=0644

- cron: name="oneill" minute="*/2" job="run-one /usr/local/bin/oneill >> /var/log/oneill.log 2>&1"
